singleQuote: false
useTabs: false
tabWidth: 2
trailingComma: all
semi: true
arrowParens: always

plugins:
  - prettier-plugin-tailwindcss
  - '@trivago/prettier-plugin-sort-imports'

# prettier-plugin-tailwindcss config
tailwindFunctions:
  - cn
  - cva
  - clsx

# @trivago/prettier-plugin-sort-imports config
importOrder:
  - '<THIRD_PARTY_MODULES>'
  - '^@/lib/(.*)$'
  - '^@/components/ui/(.*)$'
  - '^@/components/(.*)$'
  - '^@/hooks/(.*)$'
  - '^@/common/(.*)$'
  - '^@/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
