// Aggregate value types (not generated by Prisma as they're stored as JSON)

interface DurationAggregateValue {
  type: "duration";
  value: number;
}

interface NumberAggregateValue {
  type: "number";
  value: number;
}

interface StringAggregateValue {
  type: "string";
  value: string;
}

interface PercentageAggregateValue {
  type: "percentage";
  value: number; // Float between 0 and 1
}

export type AggregateValue =
  | DurationAggregateValue
  | NumberAggregateValue
  | StringAggregateValue
  | PercentageAggregateValue;

// Badge variant type (stored as JSON in Prisma)
export interface BadgeVariant {
  description: string;
  svg_url: string;
  requirement?: string | null;
}

