#!/usr/bin/env tsx
/**
 * Copy theme.css from data repository to overrides.gen.css
 * This allows users to customize the theme by placing a theme.css file in their data repo
 */

import { readFile, writeFile, access } from "fs/promises";
import { resolve } from "path";

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  // Get data directory from env or use default
  // Script is in apps/leaderboard-web/scripts, so data is at ../../../data
  const dataDir = process.env.LEADERBOARD_DATA_DIR || "../../../data";
  const themePath = resolve(import.meta.dirname, dataDir, "theme.css");
  const outputPath = resolve(import.meta.dirname, "../app/overrides.gen.css");

  console.log("🎨 Copying theme customizations...");
  console.log(`   Data directory: ${dataDir}`);
  console.log(`   Theme source: ${themePath}`);
  console.log(`   Output: ${outputPath}`);

  try {
    if (await fileExists(themePath)) {
      // Copy theme.css to overrides.gen.css
      const themeContent = await readFile(themePath, "utf-8");
      await writeFile(
        outputPath,
        `/* Auto-generated from ${dataDir}/theme.css */\n/* Do not edit this file directly - edit theme.css in your data repository instead */\n\n${themeContent}`
      );
      console.log("   ✓ Theme customizations applied");
    } else {
      // Create empty overrides.gen.css
      await writeFile(
        outputPath,
        `/* Auto-generated file */\n/* No theme.css found in data repository */\n/* Place a theme.css file in your data repository to customize the theme */\n`
      );
      console.log("   ℹ No theme.css found, using default theme");
    }
  } catch (error) {
    console.error("   ✗ Failed to copy theme:", error);
    // Create empty file as fallback
    await writeFile(
      outputPath,
      `/* Auto-generated file */\n/* Error loading theme.css */\n`
    );
    process.exit(1);
  }
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
