import { getDb } from "@/lib/db";
import { getConfig } from "@leaderboard/core";
import fs from "fs";
import path from "path";

// Output file path
const outputPath = path.resolve("app/icons.gen.ts");

// Get unique icon names from database and config
async function getIconNames() {
  const db = getDb();
  const config = getConfig();

  // Get icons from activity definitions
  const result = await db.query<{ icon: string }>(`
        SELECT DISTINCT icon FROM activity_definition WHERE icon IS NOT NULL;
    `);
  const activityIcons = result.rows.map((row) => row.icon);

  // Get icons from social profiles config
  const socialProfileIcons = config.leaderboard.social_profiles
    ? Object.values(config.leaderboard.social_profiles).map(
        (profile) => profile.icon
      )
    : [];

  // Combine and deduplicate
  const allIcons = [...new Set([...activityIcons, ...socialProfileIcons])];

  return allIcons;
}

// Convert kebab-case to PascalCase for Lucide exports
const toPascalCase = (str: string) =>
  str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

async function main() {
  const iconNames = await getIconNames();

  // Generate import statements
  const imports = iconNames
    .map((name) => `import { ${toPascalCase(name)} } from "lucide-react";`)
    .join("\n");

  // Generate map entries
  const mapEntries = iconNames
    .map((name) => `  "${name}": ${toPascalCase(name)},`)
    .join("\n");

  const content = `// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT (generated on ${new Date().toISOString()})
// This file is automatically generated by the \`pnpm generate:icons\` command.

import { LucideProps } from "lucide-react";
import { ForwardRefExoticComponent, RefAttributes } from "react";

${imports}

export const icons = {
${mapEntries}
} as {
  [key: string]: ForwardRefExoticComponent<
    Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
  >;
};
`;

  // Ensure output directory exists
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  // Write file
  fs.writeFileSync(outputPath, content);

  console.log(
    `✅ Generated ${iconNames.length} icon${
      iconNames.length !== 1 ? "s" : ""
    } → app/icons.gen.ts`
  );
}

main();
