import { access, readFile, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, "../../..");
const dataDir = process.env.LEADERBOARD_DATA_DIR || "./data";

const themePath = path.resolve(workspaceRoot, dataDir, "theme.css");
const outputPath = path.resolve(__dirname, "../app/overrides.gen.css");

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  console.log("🎨 Copying theme customizations...");
  console.log(`   Data directory: ${dataDir}`);
  console.log(`   Theme source: ${themePath}`);
  console.log(`   Output: ${outputPath}`);

  try {
    if (await fileExists(themePath)) {
      // Copy theme.css to overrides.gen.css
      const themeContent = await readFile(themePath, "utf-8");
      await writeFile(
        outputPath,
        `/* Auto-generated from ${dataDir}/theme.css */\n/* Do not edit this file directly - edit theme.css in your data repository instead */\n\n${themeContent}`
      );
      console.log("   ✓ Theme customizations applied");
    } else {
      // Create empty overrides.gen.css
      await writeFile(
        outputPath,
        `/* Auto-generated file */\n/* No theme.css found in data repository */\n/* Place a theme.css file in your data repository to customize the theme */\n`
      );
      console.log("   ℹ No theme.css found, using default theme");
    }
  } catch (error) {
    console.error("   ✗ Failed to copy theme:", error);
    // Create empty file as fallback
    await writeFile(
      outputPath,
      `/* Auto-generated file */\n/* Error loading theme.css */\n`
    );
    process.exit(1);
  }
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
