import { getConfig } from "@/lib/config/get-config";
import { getDatabase } from "@/lib/db/client";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

// Output file path for the generated icons
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const iconsPath = path.resolve(__dirname, "../app/icons.gen.ts");

// Get unique icon names from database and config
async function getIconNames() {
  const db = getDatabase();
  const config = getConfig();

  const allIcons = new Set<string>();

  // Get icons from activity definitions
  const result = await db.execute(
    "SELECT DISTINCT icon FROM activity_definition WHERE icon IS NOT NULL;"
  );
  result.rows.forEach((row) => allIcons.add(row.icon as string));

  // Get icons from social profiles config
  Object.values(config.leaderboard.social_profiles ?? []).forEach(({ icon }) =>
    allIcons.add(icon)
  );

  return allIcons;
}

// Convert kebab-case to PascalCase for Lucide exports
const toPascalCase = (str: string) =>
  str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

async function main() {
  const iconNames = Array.from(await getIconNames());

  // Generate import statements
  const imports = iconNames
    .map((name) => `import { ${toPascalCase(name)} } from "lucide-react";`)
    .join("\n");

  // Generate map entries
  const mapEntries = iconNames
    .map((name) => `  "${name}": ${toPascalCase(name)},`)
    .join("\n");

  const content = `// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT (generated on ${new Date().toISOString()})
// This file is automatically generated by the \`pnpm generate:icons\` command.

import { LucideProps } from "lucide-react";
import { ForwardRefExoticComponent, RefAttributes } from "react";

${imports}

export const icons = {
${mapEntries}
} as {
  [key: string]: ForwardRefExoticComponent<
    Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>
  >;
};
`;

  await mkdir(path.dirname(iconsPath), { recursive: true });
  await writeFile(iconsPath, content);

  console.log(`Generated ${iconNames.length} icon(s) → ${iconsPath}`);
}

main();
