on:
  workflow_call:
    secrets:
      SLACK_EOD_BOT_WEBHOOK:
        required: true

jobs:
  main:
    name: Fetch activity from GitHub and call Slack Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # This pulls the caller workflow's repo (eg: coronasafe/leaderboard-data)

      - uses: actions/checkout@v4
        with:
          repository: coronasafe/leaderboard
          path: ./leaderboard
          sparse-checkout: scripts

      - uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - run: npm install @octokit/action gray-matter

      - run: node scripts/slackEODReminder.js
        env:
          GITHUB_ORG: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_EOD_BOT_WEBHOOK_URL: ${{ secrets.SLACK_EOD_BOT_WEBHOOK }}
